# shellcheck shell=bash
# Recipe: build a .bs from a declarative recipe that fetches a real upstream
# artifact (e.g. Krita's official AppImage), verifies its checksum, lays out a
# package directory and hands it to the packager. A recipe is a small bash file
# authored by the packager — trusted, like a PKGBUILD — sourced in a scoped way.
#
# A recipe sets: name, version, arch, os, exec (required) and optionally
# pretty_name, comment, categories, icon, terminal, bundle_libs, isolate_home.
# To obtain the files it either:
#   - declares source_url + source_type (appimage|tar|file) [+ source_sha256], or
#   - defines a prepare() function that populates $pkgdir (using bs_fetch etc.).

# --- helpers exposed to recipes ---------------------------------------------

# bs_fetch URL DEST [SHA256] — fetch URL to DEST, verifying sha256 if given.
# A local path or file:// URL is copied directly (handy for offline recipes/tests).
bs_fetch() {
	local url="$1" dest="$2" want="${3:-}" src="$1"
	[[ "$src" == file://* ]] && src="${src#file://}"
	if [[ -f "$src" ]]; then
		ui::info "copying $src"
		cp -- "$src" "$dest" || { ui::error "copy failed: $src"; return 1; }
	else
		ui::info "fetching $url"
		if command -v curl >/dev/null 2>&1; then
			curl -fL --retry 2 -o "$dest" -- "$url" || { ui::error "download failed: $url"; return 1; }
		elif command -v wget >/dev/null 2>&1; then
			wget -q -O "$dest" -- "$url" || { ui::error "download failed: $url"; return 1; }
		else
			ui::error "need curl or wget to fetch sources"; return 127
		fi
	fi
	if [[ -n "$want" ]]; then
		command -v sha256sum >/dev/null 2>&1 || { ui::error "sha256sum needed to verify source"; return 127; }
		local got; got="$(sha256sum "$dest" | cut -d' ' -f1)"
		if [[ "$got" != "$want" ]]; then
			ui::error "source sha256 mismatch"
			ui::info "  want $want"
			ui::info "  got  $got"
			return 1
		fi
		ui::ok "source sha256 verified"
	else
		ui::warn "no source_sha256 given — using the download unverified"
	fi
}

# bs_appimage_extract FILE DESTDIR — extract an AppImage's tree into DESTDIR.
# Needs a Linux host of the matching architecture (the AppImage self-extracts).
bs_appimage_extract() {
	local file="$1" dest="$2" wd
	chmod +x "$file" 2>/dev/null || true
	wd="$(mktemp -d)"
	if ( cd "$wd" && "$file" --appimage-extract >/dev/null 2>&1 ) && [[ -d "$wd/squashfs-root" ]]; then
		mkdir -p "$dest"; cp -a "$wd/squashfs-root/." "$dest/"
		rm -rf "$wd"
	else
		rm -rf "$wd"
		ui::error "AppImage extraction failed (need a Linux host of the right architecture)"
		return 1
	fi
}

# --- runner -----------------------------------------------------------------

recipe::_write_manifest() {
	{
		printf '# generated by bs make from a recipe\n'
		printf 'name = %s\n'    "$name"
		printf 'version = %s\n' "$version"
		printf 'arch = %s\n'    "$arch"
		printf 'os = %s\n'      "$os"
		printf 'exec = %s\n'    "$exec"
		[[ -n "${pretty_name:-}" ]] && printf 'pretty_name = %s\n' "$pretty_name"
		[[ -n "${comment:-}" ]]     && printf 'comment = %s\n'     "$comment"
		[[ -n "${categories:-}" ]]  && printf 'categories = %s\n'  "$categories"
		[[ -n "${icon:-}" ]]        && printf 'icon = %s\n'        "$icon"
		printf 'terminal = %s\n'     "${terminal:-false}"
		printf 'bundle_libs = %s\n'  "${bundle_libs:-false}"
		printf 'isolate_home = %s\n' "${isolate_home:-false}"
		[[ -n "${min_glibc:-}" ]] && printf 'min_glibc = %s\n' "$min_glibc"
	} > "$1"
}

# Default layout when the recipe declares source_url instead of its own prepare().
recipe::_default_prepare() {
	[[ -n "${source_url:-}" ]] || { ui::error "recipe defines neither prepare() nor source_url"; return 1; }
	local dl="$srcdir/download"
	bs_fetch "$source_url" "$dl" "${source_sha256:-}" || return 1
	case "${source_type:-}" in
		appimage) bs_appimage_extract "$dl" "$pkgdir" ;;
		tar)      tar -xf "$dl" -C "$pkgdir" || { ui::error "tar extract failed"; return 1; } ;;
		file)     mkdir -p "$pkgdir/$(dirname -- "$exec")"; cp -- "$dl" "$pkgdir/$exec" ;;
		*)        ui::error "set source_type to appimage|tar|file (got '${source_type:-}')"; return 1 ;;
	esac
}

# recipe::run RECIPE [-o OUT]
# Thin wrapper: parse args, make a workspace, run the build, always clean up.
# (No RETURN trap — it would also fire when `source "$recipe"` finishes and wipe
# the workspace mid-build.)
recipe::run() {
	local recipe="" out=""
	while (($#)); do
		case "$1" in
			-o|--output) shift; out="${1:-}" ;;
			-*) ui::error "unknown make option: $1"; return 2 ;;
			*) if [[ -z "$recipe" ]]; then recipe="$1"; else ui::error "unexpected argument: $1"; return 2; fi ;;
		esac
		shift
	done
	[[ -n "$recipe" ]] || { ui::error "$(i18n::t err_make_usage)"; return 2; }
	[[ -f "$recipe" ]] || { ui::error "$(i18n::t err_not_found "$recipe")"; return 1; }

	local work rc=0
	work="$(mktemp -d)"
	recipe::_build "$work" "$recipe" "$out" || rc=$?
	rm -rf "$work"
	return "$rc"
}

# recipe::_build WORK RECIPE OUT
# Recipe fields are locals here so the sourced recipe (and its prepare()) see and
# set them via dynamic scope.
recipe::_build() {
	local work="$1" recipe="$2" out="$3"
	local name="" version="" arch="" os="" exec="" pretty_name="" comment=""
	local categories="" icon="" terminal="" bundle_libs="" isolate_home=""
	local source_url="" source_sha256="" source_type="" min_glibc=""
	local srcdir="$work/src" pkgdir="$work/pkg"
	mkdir -p "$srcdir" "$pkgdir"
	# Directory of the recipe, so a recipe can reference its own sources.
	# Exported so the sourced recipe (and any tool it runs) can read it.
	local RECIPE_DIR
	RECIPE_DIR="$(cd -- "$(dirname -- "$recipe")" && pwd)"
	export RECIPE_DIR

	# A recipe is the packager's own trusted build script (cf. PKGBUILD/formula).
	# shellcheck disable=SC1090
	source "$recipe"

	local v
	for v in name version arch os exec; do
		[[ -n "${!v}" ]] || { ui::error "recipe missing required field: $v"; return 1; }
	done

	if declare -F prepare >/dev/null 2>&1; then
		prepare || { ui::error "recipe prepare() failed"; return 1; }
		unset -f prepare
	else
		recipe::_default_prepare || return 1
	fi

	recipe::_write_manifest "$pkgdir/manifest"

	[[ -n "$out" ]] || out="$name-$version-$arch.bs"
	pack::build "$pkgdir" -o "$out"
}
